// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDfXLpn4lNMAshpqAQH-1tx_yxqnkOX-kY',
    appId: '1:565304800533:web:6613555fcc3b5b7031251c',
    messagingSenderId: '565304800533',
    projectId: 'aquae-ca006',
    authDomain: 'aquae-ca006.firebaseapp.com',
    storageBucket: 'aquae-ca006.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBNOd7sovF-CJ4SkJlSGhsuPdMNv-jbAX0',
    appId: '1:565304800533:android:c2083b2018a9165831251c',
    messagingSenderId: '565304800533',
    projectId: 'aquae-ca006',
    storageBucket: 'aquae-ca006.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD_CgI9PwHRHpO3jgki1arDyARD6l7Ness',
    appId: '1:565304800533:ios:6d512df7b449247c31251c',
    messagingSenderId: '565304800533',
    projectId: 'aquae-ca006',
    storageBucket: 'aquae-ca006.appspot.com',
    iosBundleId: 'com.example.aquae',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD_CgI9PwHRHpO3jgki1arDyARD6l7Ness',
    appId: '1:565304800533:ios:6d512df7b449247c31251c',
    messagingSenderId: '565304800533',
    projectId: 'aquae-ca006',
    storageBucket: 'aquae-ca006.appspot.com',
    iosBundleId: 'com.example.aquae',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDfXLpn4lNMAshpqAQH-1tx_yxqnkOX-kY',
    appId: '1:565304800533:web:19dadb6bf900e3e131251c',
    messagingSenderId: '565304800533',
    projectId: 'aquae-ca006',
    authDomain: 'aquae-ca006.firebaseapp.com',
    storageBucket: 'aquae-ca006.appspot.com',
  );
}
